export const FETCH_POST_LIST = 'FETCH_POST_LIST';
export const FETCH_POST = 'FETCH_POST';

export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
